### ISSUE TITLE
Lambda's failing after latest update.

### ISSUE THREAD

**Issue by dking6902** [wavefrontHQ/wavefront-pyformance#22] opened 2019-03-07 15:51 UTC
Hi, 
I have a number of lambdas that use boto3 to query the AWS API and then send customised gauge metrics to Wavefront.

Since the update of wavefront_pyformance to 0.9.3, I am getting the following error, and all of my Lambda's fail.

[ERROR] Runtime.ImportModuleError: Unable to import module "lambda_handler'': No module named 'accumulation_tree.accumulation_tree'

I have rolled back wavefront_pyformance to 0.9.2 and it is working again.

I believe there may be an issue with the update (or my bad coding)

Kind regards

Daniel

**Comment by vikramraman** [comment] 2019-03-07 18:08
Thanks for raising the issue @dking6902 . We will update our lambda library to be compatible with 0.9.3.

**Comment by akodali18** [comment] 2019-03-14 21:41
@dking6902  I am unable to reproduce this issue on wavefront_pyformance 0.9.3 (I ran the sample thumbnail service lambda published by aws which also uses boto3 ->   https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example-deployment-pkg.html  and followed the steps to create a deployment package for python in the above link). I am suspecting an issue with the package you uploaded to aws lambda. Could you retry your lambda with wavefront_pyformance 0.9.3 in a new python virtualenv to void out any issues with the deployment package in the update process.

In case i missed something, Please do let me know the steps to reproduce the issue.

**Comment by akodali18** [comment] 2019-03-22 18:35
Closing assuming this was a lambda packaging issue. Please feel free to revert with specific steps to repro.

**Comment by akodali18** [comment] 2019-04-15 22:14
@dking6902 I was able to repro this issue.
Our `wavefront-sdk-python` uses `tdigest` which uses the dependency `accumulation_tree` …..  accumulation_tree is a .pyx file -> https://github.com/tkluck/accumulation_tree/blob/master/accumulation_tree/accumulation_tree.pyx 

The AWS Lambda environment will not be able to execute this unless you also include `Cython` as a dependency in your lambda package.

**Comment by ustinov** [comment] 2019-06-18 22:55
Closing this as not an issue. The `accumulation_tree` mentioned above is a binary dependency of `tdigest` and in order to package it correctly, one must use the same packaging environment as AWS lambda environment is (https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). 
Pay attention to Python version, kernel version, libc version, etc. and make sure you use `-t` flag when running `pip install -t ~/$PATH_TO_YOUR_LAMBDA_PKG wavefront-pyformance`.

**Closed as completed by ustinov** 2019-06-18 22:55 UTC
